"""
PDF text extraction service using PyMuPDF (fitz).
Extracts spans with full metadata from all pages.
"""
from __future__ import annotations
import math
import re
import uuid
from pathlib import Path
from typing import BinaryIO

import fitz  # PyMuPDF

from schemas.pdf import BoundingBox, ExtractionResult, PdfSpan
from services.classifier import classify_span


# Minimum text length to be considered a candidate field
_MIN_TEXT_LEN = 1
# Skip spans that are only whitespace or single punctuation
_SKIP_PATTERN = re.compile(r"^[\s\.\-\_\|:,;\*]+$")
# Pattern specifically for tall vertical line artifacts generated by OCR
_TALL_ARTIFACT_PATTERN = re.compile(r"^[\s\.\-\_\|:,;\'\"lI1i\[\]\(\)]+$")


def _normalize_text(raw: str) -> str:
    """Trim and collapse internal whitespace."""
    return re.sub(r"\s+", " ", raw).strip()


def _unpack_color(color_int: int) -> tuple[int, int, int]:
    """Unpack a packed RGB int (PyMuPDF sRGB) into (r, g, b)."""
    r = (color_int >> 16) & 0xFF
    g = (color_int >> 8) & 0xFF
    b = color_int & 0xFF
    return r, g, b


def _line_dir_to_text_rotation(dir_xy) -> int:
    """
    Map MuPDF line ``dir`` (cos, sin) to ``Page.insert_text`` rotate (0, 90, 180, 270).

    Require a *strong* horizontal or vertical baseline. Noisy ``dir`` near form edges
    was snapping almost-horizontal text to 90°, so export drew vertical glyphs on top
    of table cells (garbled blocks in the rightmost columns).
    """
    try:
        dx = float(dir_xy[0])
        dy = float(dir_xy[1])
    except (TypeError, ValueError, IndexError):
        return 0
    hyp = math.hypot(dx, dy)
    if hyp < 1e-6:
        return 0
    dx, dy = dx / hyp, dy / hyp
    # LTR / RTL horizontal
    if abs(dy) < 0.2 and abs(dx) > 0.75:
        return 180 if dx < 0 else 0
    # Vertical (baseline along y in page space)
    if abs(dx) < 0.2 and abs(dy) > 0.75:
        return 90 if dy < 0 else 270
    return 0


def _span_bbox_to_display_rect(page: fitz.Page, bbox_tuple: tuple) -> fitz.Rect:
    """
    Map a span's axis-aligned bbox into the same coordinate space as ``page.rect``.

    MuPDF reports span bboxes in **unrotated** page space even when the page has a
    non-zero ``/Rotate`` entry. After rotation, ``page.rect`` dimensions match the
    **viewer's** page (same as PDF.js ``getViewport({scale: 1})``), so we must apply
    ``page.rotation_matrix`` before subtracting ``page.rect`` origin. Otherwise
    overlays and page sizes disagree and boxes appear shifted, scaled, or on the
    wrong rows.
    """
    r = fitz.Rect(bbox_tuple)
    r *= page.rotation_matrix
    return r.normalize()


def extract_spans(
    file_bytes: bytes, 
    filename: str = "document.pdf", 
    selected_pages: list[int] | None = None
) -> ExtractionResult:
    """
    Open a PDF from bytes and extract all text spans with metadata.
    Returns an ExtractionResult with structured PdfSpan objects.
    
    If selected_pages is provided, only extracts those 0-indexed indices.
    Maximum 5 pages allowed per extraction.
    """
    doc = fitz.open(stream=file_bytes, filetype="pdf")
    total_doc_pages = len(doc)
    
    # DETERMINE PAGES TO PROCESS
    pages_to_process = selected_pages
    if pages_to_process is None:
        pages_to_process = list(range(total_doc_pages))

    all_spans: list[PdfSpan] = []
    page_sizes: list[dict] = []

    for page_idx in pages_to_process:
        if page_idx < 0 or page_idx >= total_doc_pages:
            doc.close()
            raise ValueError(f"Page Index Out of Bounds: {page_idx}. Document has {total_doc_pages} pages.")

        page = doc[page_idx]
        rect = page.rect  # page dimensions in pts

        page_sizes.append({
            "page": page_idx,
            "width": rect.width,
            "height": rect.height,
        })

        # get_text("dict") returns nested blocks → lines → spans
        text_dict = page.get_text("dict", flags=fitz.TEXT_PRESERVE_WHITESPACE)

        for block in text_dict.get("blocks", []):
            # Only process text blocks (type 0), not image blocks (type 1)
            if block.get("type") != 0:
                continue

            for line in block.get("lines", []):
                for span in line.get("spans", []):
                    raw_text: str = span.get("text", "")
                    normalized = _normalize_text(raw_text)

                    # Skip empty / whitespace-only / punctuation-only spans
                    if len(normalized) < _MIN_TEXT_LEN:
                        continue
                    if _SKIP_PATTERN.match(normalized):
                        continue

                    bbox_tuple = span.get("bbox", (0, 0, 0, 0))
                    disp = _span_bbox_to_display_rect(page, bbox_tuple)
                    # Normalize to page.rect origin (crop/mediabox intersection in display space)
                    x0 = disp.x0 - rect.x0
                    y0 = disp.y0 - rect.y0
                    x1 = disp.x1 - rect.x0
                    y1 = disp.y1 - rect.y0

                    width = x1 - x0
                    height = y1 - y0

                    # Calculate and normalize visual baseline origin coordinates
                    origin_tuple = span.get("origin", (bbox_tuple[0], bbox_tuple[3]))
                    disp_origin = fitz.Point(origin_tuple) * page.rotation_matrix
                    origin_x = disp_origin.x - rect.x0
                    origin_y = disp_origin.y - rect.y0

                    # Skip zero-size spans
                    if width <= 0 or height <= 0:
                        continue

                    # Heuristics to eliminate OCR phantom vertical lines and artifacts:
                    # 1. Extreme aspect ratio (4x taller than wide) is purely an artifact
                    if height > (width * 4):
                        continue
                    
                    # 2. Moderately tall (e.g. >35pt) but narrow (<25pt) matching artifact chars
                    if height > 35 and width < 25 and _TALL_ARTIFACT_PATTERN.match(normalized):
                        continue

                    # 3. Overall bizarrely tall (>80pt) but containing very few generic characters
                    if height > 80 and len(normalized) <= 4 and _TALL_ARTIFACT_PATTERN.match(normalized):
                        continue

                    font_name: str = span.get("font", "unknown") or "unknown"
                    font_size: float = float(span.get("size", 12.0))

                    # Color: PyMuPDF returns an int (sRGB packed)
                    color_val = span.get("color", 0)
                    if isinstance(color_val, (list, tuple)):
                        # Some versions return RGB tuple 0..1
                        r = int(color_val[0] * 255)
                        g = int(color_val[1] * 255)
                        b = int(color_val[2] * 255)
                        color_int = (r << 16) | (g << 8) | b
                    else:
                        color_int = int(color_val)

                    flags: int = span.get("flags", 0)
                    field_type = classify_span(normalized)
                    text_rotation = _line_dir_to_text_rotation(line.get("dir", (1.0, 0.0)))

                    # Estimate letter spacing
                    letter_spacing = 0.0
                    if len(raw_text) > 1:
                        try:
                            # Use internal PyMuPDF font metrics to find natural width
                            # We check if natural base 14 mapped font is narrower than bounding box
                            from services.exporter import _get_font_name
                            mapped_font = _get_font_name(font_name, flags)
                            f = fitz.Font(fontname=mapped_font)
                            natural_width = f.text_length(raw_text, fontsize=font_size)
                            # Only consider substantial spacing (> 0.1em) as explicit letter_spacing
                            if width > natural_width + (font_size * 0.1):
                                letter_spacing = (width - natural_width) / len(raw_text)
                        except Exception:
                            pass

                    pdf_span = PdfSpan(
                        id=str(uuid.uuid4()),
                        page=page_idx,
                        text=normalized,
                        raw_text=raw_text,
                        bbox=BoundingBox(x0=x0, y0=y0, x1=x1, y1=y1),
                        x=x0,
                        y=y0,
                        width=width,
                        height=height,
                        origin_x=origin_x,
                        origin_y=origin_y,
                        font=font_name,
                        size=font_size,
                        color=color_int,
                        flags=flags,
                        field_type=field_type,
                        letter_spacing=letter_spacing,
                        text_rotation=text_rotation,
                    )
                    all_spans.append(pdf_span)

    page_count = len(doc)
    doc.close()

    return ExtractionResult(
        filename=filename,
        page_count=page_count,
        page_sizes=page_sizes,
        spans=all_spans,
    )

